# Generated by Django 4.2.20 on 2025-04-16 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=64)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("url", models.URLField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SocialPlatform",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(help_text="service where this tech group is hosted", max_length=64, unique=True),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("base_url", models.URLField(blank=True, help_text="base url of provider")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("value", models.CharField(max_length=64, unique=True)),
            ],
            options={
                "ordering": ["value"],
            },
        ),
        migrations.CreateModel(
            name="TechGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("description", models.TextField(blank=True)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Font Awesome CSS icon class(es) to represent the group.", max_length=255
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="techgroups/")),
                ("links", models.ManyToManyField(blank=True, to="web.link")),
                ("platform", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.socialplatform")),
                ("tags", models.ManyToManyField(blank=True, to="web.tag")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("start_datetime", models.DateTimeField(help_text="date and time the event starts")),
                ("end_datetime", models.DateTimeField(help_text="date and time the event ends", null=True)),
                (
                    "location_name",
                    models.CharField(
                        blank=True, help_text="name of location where this event is being hosted", max_length=64
                    ),
                ),
                (
                    "location_address",
                    models.CharField(
                        blank=True, help_text="address of location where this event is being hosted", max_length=256
                    ),
                ),
                ("map_link", models.URLField(blank=True, help_text="link to a map showing the location of the event")),
                ("url", models.URLField(blank=True, help_text="URL to the event details")),
                (
                    "social_platform_id",
                    models.CharField(
                        blank=True,
                        help_text="unique identifier provided by the social platform hosting the event",
                        max_length=128,
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="tech_events/")),
                (
                    "group",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="web.techgroup"
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="web.tag")),
            ],
            options={
                "ordering": ["start_datetime"],
            },
        ),
    ]
