# Generated by Django 4.2.20 on 2025-09-04 20:53

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_alter_event_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["start_datetime"]},
        ),
        migrations.AddField(
            model_name="techgroup",
            name="discord_webhook_url",
            field=encrypted_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
