# Generated by Django 4.2.20 on 2025-10-30 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_alter_event_options_techgroup_discord_webhook_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="end_datetime",
            field=models.DateTimeField(blank=True, help_text="date and time the event ends", null=True),
        ),
    ]
