# Generated by Django 4.2.20 on 2025-04-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="title",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
