name: Import Order Validation (isort)

on:
  push:
    branches-ignore:
      - main

jobs:
  isort:
    runs-on: ubuntu-latest
    name: "isort"
    if: github.event.created == false  # Skip if this push created a new branch
    steps:
      - uses: davidslusser/actions_python_isort@v1.0.1
        with:
          src: "src/django_project"
          options: "--check --diff"
          python_version: "3.13"
